# Generated by Django 5.1.1 on 2024-09-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_list_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
