# Generated by Django 5.1.1 on 2024-09-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
