# Generated by Django 3.2.25 on 2024-07-10 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0024_dataset_embedding_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(default='-', max_length=200)),
                ('component_type', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Datasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasheet_name', models.CharField(default='-', max_length=200)),
                ('datasheet_size', models.IntegerField(default=0)),
                ('data_file', models.FileField(default='-', upload_to='datasheets')),
                ('datasheet_date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.CharField(default='-', max_length=200)),
                ('user_email', models.CharField(default='-', max_length=200)),
                ('user_group', models.CharField(default='-', max_length=200)),
            ],
            options={
                'verbose_name': 'datasheet',
                'verbose_name_plural': 'datasheets',
            },
        ),
        migrations.CreateModel(
            name='FeaturePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='chunks',
            name='chunk_dataset',
        ),
        migrations.RemoveField(
            model_name='chunks',
            name='chunk_paper',
        ),
        migrations.RemoveField(
            model_name='chunks',
            name='chunk_video',
        ),
        migrations.DeleteModel(
            name='FrontEndSettings',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='paper_dataset',
        ),
        migrations.RemoveField(
            model_name='source',
            name='chunk',
        ),
        migrations.RemoveField(
            model_name='source',
            name='question',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='video_dataset',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='pca_x',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='pca_y',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='pca_z',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='relevance_score',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_dataset',
        ),
        migrations.RemoveField(
            model_name='question',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pca_x',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pca_y',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pca_z',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_dataset',
        ),
        migrations.RemoveField(
            model_name='question',
            name='relevance_score',
        ),
        migrations.AddField(
            model_name='answer',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.conversation'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.conversation'),
        ),
        migrations.DeleteModel(
            name='chunks',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.AddField(
            model_name='component',
            name='component_features',
            field=models.ManyToManyField(to='testdb.FeaturePair'),
        ),
        migrations.AddField(
            model_name='answer',
            name='datasheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.datasheet'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_datasheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.datasheet'),
        ),
        migrations.AddField(
            model_name='question',
            name='datasheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.datasheet'),
        ),
    ]
