# Generated by Django 5.0.7 on 2024-08-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0026_answer_answer_type_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='component_features',
        ),
        migrations.RemoveField(
            model_name='component',
            name='component_name',
        ),
        migrations.AddField(
            model_name='component',
            name='component_info',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.TextField(default='-'),
        ),
        migrations.DeleteModel(
            name='FeaturePair',
        ),
    ]
